name: Build and push dockerdl-base image
on:
  schedule:
    # Runs at 00:10 am every Sunday
    - cron: "10 0 * * 0"
  push:
    branches: ["main"]
    paths:
      - "base.Dockerfile"
      - ".github/workflows/docker-publish-base.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "base.Dockerfile"
      - ".github/workflows/docker-publish-base.yml"
  workflow_dispatch:

concurrency:
  group: dockerdl-base-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        CUDA_VER: [12.1.1, 11.8.0]
    env:
      depot: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'}}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            matifali/dockerdl-base
          tags: |
            type=raw,value=${{ matrix.CUDA_VER }}
            type=raw,value=latest,enable=${{ matrix.CUDA_VER == '12.1.1' }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
            org.opencontainers.image.authors=${{ github.event.repository.owner.login }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker buildx
        if: ${{ env.depot == false }}
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        if: ${{ env.depot == false }}
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: base.Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: CUDA_VER=${{ matrix.CUDA_VER }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup Depot
        if: ${{ env.depot == true }}
        uses: depot/setup-action@v1
      
      - name: Build and Push with Depot.dev
        if: ${{ env.depot == true }}
        uses: depot/build-push-action@v1
        with:
          project: 2v54ngnx2v
          context: .
          file: base.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: depot
          client-payload: '{"depot": "${{ env.depot }}"}'

