name: Build and push dockerdl images
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and push dockerdl-base image"]
    branches: ["main"]
    types:
      - completed

concurrency:
  group: dockerdl-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./conda.Dockerfile
            tag: conda
          - dockerfile: ./tf-torch-conda.Dockerfile
            tag: tf-torch-conda
          - dockerfile: ./tf-torch.Dockerfile
            tag: tf-torch
          - dockerfile: ./torch.Dockerfile
            tag: torch
          - dockerfile: ./tf.Dockerfile
            tag: tf
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            matifali/dockerdl
          tags: |
            type=raw,value=${{ matrix.tag }}
            type=raw,value=latest,enable=${{ matrix.tag == 'tf-torch' }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
            org.opencontainers.image.authors=${{ github.event.repository.owner.login }}
            
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker buildx
        if: github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v2
   
      - name: Build and push Docker image
        if: github.event_name == 'workflow_dispatch'
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Setup Depot
        uses: depot/setup-action@v1
      
      - name: Build and Push with Depot.dev
        if: github.event_name == 'workflow_run'
        uses: depot/build-push-action@v1
        with:
          project: 2v54ngnx2v
          file: ${{ matrix.dockerfile }}
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Readme on dockerhub
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: matifali/dockerdl
          short-description: ${{ github.event.repository.description }}
          readme-filepath: README.md
